name: Build

on: workflow_dispatch

jobs:
	windows_x86:
		name: Windows (x86)
		runs-on: ubuntu-latest
		steps:
			- uses: actions/checkout@v2
			- uses: actions-rs/toolchain@1
			with:
				toolchain: stable
				target:
				overwrite: true
			- uses: actions-rs/cargo@v1
			with:
				use-cross: true
				command: build
				args: --release --target x86_64-pc-windows-gnu
