name: Build

on: workflow_dispatch

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc, aarch64-pc-windows-msvc
      - name: Build for Windows (x86)
        run: cargo build --release --target x86_64-pc-windows-msvc
      - name: Build for Windows (ARM)
        run: cargo build --release --target aarch64-pc-windows-msvc
  macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin, aarch64-apple-darwin
      - name: Build for macOS (x86)
        run: cargo build --release --target x86_64-apple-darwin
      - name: Build for macOS (ARM)
        run: cargo build --release --target aarch64-apple-darwin
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu
      - name: Build for Linux (x86)
        run: cargo build --release --target x86_64-unknown-linux-gnu
